; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = bloated_mp3_player

[env:bloated_mp3_player]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	olikraus/U8g2@^2.36.0
build_flags = 
	-Os
	-DBOARD_HAS_PSRAM
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Wall -Wextra
	-Warray-bounds
	-Wno-unused-parameter
	-DPIO_FRAMEWORK_ARDUINO_CPP_NO_MAIN
	-DHSPI=1
lib_ldf_mode = chain
extra_scripts = pre:middleware/full_erase.py
build_src_filter = +<*> -<main.old.cpp>

[env:test]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
test_framework = unity
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	olikraus/U8g2@^2.36.0
build_flags = 
	-Os
	-DBOARD_HAS_PSRAM
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Wall -Wextra
	-Wno-unused-parameter
	-DPIO_FRAMEWORK_ARDUINO_CPP_NO_MAIN
	-DHSPI=1
lib_ldf_mode = chain
build_src_filter = +<*> -<main.old.cpp>
