; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = diy-esp32-s3-devkit
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	olikraus/U8g2@^2.36.0
build_flags = 
	-Os
	-DBOARD_HAS_PSRAM
	-DESP32_FLASH_SIZE=4MB
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-Wall -Wextra
	-Warray-bounds
	-Wno-unused-parameter
extra_scripts = pre:middleware/full_erase.py
src_filter = +<*> -<main.old.cpp>
